{
 "title": "Tickets",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval_graphs", "label": "Graph Intervall", "query": "1h,1d,2d,7d,30d" }
  ]
 },
 "panels": [
  { "title": "General metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ticket create / close rate",
   "type": "timeseries",
   "description": "1h time range minimum",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Tickets" } },
   "targets": [
    {
     "alias": "created Tickets",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    },
    {
     "alias": "closed Tickets",
     "bucketAggs": [
      { "field": "close_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "close_at"
    }
   ]
  },
  {
   "title": "Tickets created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Tickets closed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "close_at", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "close_at"
    }
   ]
  },
  {
   "title": "Group distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Tickets" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "group.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      },
      { "field": "created_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Sender ratio",
   "type": "piechart",
   "description": "Article-Sender-IDs are **NOT** the same on every instance. Run \"Ticket::Article::Sender.find(<value>).name\"  within your rails console to get the renames (see transforms) correctly.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "article.sender_id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "article.created_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "article.id",
       "hide": false,
       "id": "1",
       "settings": { "missing": "0" },
       "type": "cardinality"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Created Articles",
   "type": "timeseries",
   "description": "1h time range minimum",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Articles" } },
   "targets": [
    {
     "alias": "Article creations",
     "bucketAggs": [
      { "field": "article.created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "article.id",
       "hide": false,
       "id": "1",
       "type": "cardinality"
      }
     ],
     "timeField": "article.created_at"
    }
   ]
  },
  {
   "title": "Article type ratio",
   "type": "piechart",
   "description": "Article-Type-IDs are **NOT** the same on every instance. Run \"Ticket::Article::Type.find(<value>)\"  within your rails console to get the renames (see transforms) correctly.",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "article.type_id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "article.created_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "article.id",
       "hide": false,
       "id": "1",
       "settings": { "missing": "0" },
       "type": "cardinality"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Content types",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Tickets" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "article.content_type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      },
      { "field": "created_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  { "title": "More details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Newest 10 tickets",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "created_at",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "created_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "field": "title.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "id", "id": "1", "settings": { "script": "_value * 1" }, "type": "sum" }
     ],
     "timeField": "created_at"
    },
    {
     "bucketAggs": [
      {
       "field": "created_at",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "created_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "field": "number.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "id", "id": "1", "settings": { "script": "_value * 1" }, "type": "sum" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Last 10 ticket updates",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "updated_at",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "updated_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "field": "title.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "id", "id": "1", "settings": { "script": "_value * 1" }, "type": "sum" }
     ],
     "timeField": "created_at"
    },
    {
     "bucketAggs": [
      {
       "field": "updated_at",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "updated_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "field": "number.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "id", "id": "1", "settings": { "script": "_value * 1" }, "type": "sum" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Last 10 closed tickets",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "close_at",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "close_at", "id": "7", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "field": "title.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "id", "id": "1", "settings": { "script": "_value * 1" }, "type": "sum" }
     ],
     "timeField": "created_at"
    },
    {
     "bucketAggs": [
      {
       "field": "close_at",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "close_at", "id": "6", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "field": "number.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "id", "id": "1", "settings": { "script": "_value * 1" }, "type": "sum" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 10 ticket tags",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "tags.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 10 owners based on Tickets",
   "type": "table",
   "description": "This shows the last owner only and may not display the real workload of each agent.",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "owner.login.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 10 organizations",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "organization.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "id",
       "id": "1",
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 10 customers based on Tickets",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "customer.login.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": true,
       "id": "1",
       "type": "count"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Average accounted time of tickets",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "group.name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "time_unit",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "time_unit: >0",
     "timeField": "close_at"
    }
   ]
  },
  { "title": "SLAs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "average first response",
   "type": "gauge",
   "description": "Negative values indicate violated SLAs",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "minutes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "first_response_diff",
     "bucketAggs": [
      { "field": "created_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "first_response_diff_in_min",
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Escalations: violations vs in time",
   "type": "timeseries",
   "description": "Some graphs *may* display current information only and thus hide historical escalations.",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Tickets" } },
   "targets": [
    {
     "alias": "First response violated",
     "bucketAggs": [
      { "field": "first_response_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "first_response_diff_in_min: <0",
     "timeField": "created_at"
    },
    {
     "alias": "First response in time",
     "bucketAggs": [
      { "field": "first_response_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "first_response_diff_in_min: >0",
     "timeField": "created_at"
    },
    {
     "alias": "Update response violated",
     "bucketAggs": [
      { "field": "update_escalation_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "update_diff_in_min: <0",
     "timeField": "created_at"
    },
    {
     "alias": "Update response in time",
     "bucketAggs": [
      { "field": "update_escalation_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "update_diff_in_min: >0",
     "timeField": "created_at"
    },
    {
     "alias": "Case solve violated",
     "bucketAggs": [
      { "field": "close_escalation_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "close_diff_in_min: <0",
     "timeField": "created_at"
    },
    {
     "alias": "Case solve in time",
     "bucketAggs": [
      { "field": "close_escalation_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "close_diff_in_min: >0",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "average update time",
   "type": "gauge",
   "description": "Negative values indicate violated SLAs",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "minutes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "update_diff",
     "bucketAggs": [
      { "field": "updated_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "update_diff_in_min", "id": "1", "type": "avg" }
     ],
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Escalation ratios",
   "type": "piechart",
   "description": "Some indicators *may* display current information only and thus hide historical escalations.",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Tickets" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "First response violated",
     "bucketAggs": [
      { "field": "first_response_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "first_response_diff_in_min: <0",
     "timeField": "created_at"
    },
    {
     "alias": "First response in time",
     "bucketAggs": [
      { "field": "first_response_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "first_response_diff_in_min: >0",
     "timeField": "created_at"
    },
    {
     "alias": "Case solve violated",
     "bucketAggs": [
      { "field": "close_escalation_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "close_diff_in_min: <0",
     "timeField": "created_at"
    },
    {
     "alias": "Case solve in time",
     "bucketAggs": [
      { "field": "close_escalation_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "close_diff_in_min: >0",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Last 10 escalated ticket",
   "type": "table",
   "description": "This shows current escalated tickets, they will disappear upon solving.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 60 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "escalation_at",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "escalation_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "field": "title.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "id", "id": "1", "settings": { "script": "_value * 1" }, "type": "sum" }
     ],
     "query": "escalation_at: <now",
     "timeField": "created_at"
    },
    {
     "bucketAggs": [
      {
       "field": "escalation_at",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "escalation_at", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "field": "number.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "id", "id": "1", "settings": { "script": "_value * 1" }, "type": "sum" }
     ],
     "query": "escalation_at: <now",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "average close time",
   "type": "gauge",
   "description": "Negative values indicate violated SLAs",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "close_diff",
     "bucketAggs": [
      { "field": "close_at", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "close_diff_in_min", "id": "1", "type": "avg" }
     ],
     "timeField": "created_at"
    }
   ]
  }
 ]
}